name: Flow Push Branches
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --all-features
      - name: Set up NodeJS   
        uses: actions/setup-node@v2
        with:
          node-version: '16'         
      - name: Install nodejs dependencies
        working-directory: dist/templating
        run: |
          npm install
      - name: Create .deb package
        working-directory: dist/templating
        run: |
          node packageDeb.js
      - name: Create .rpm package
        working-directory: dist/templating
        run: |
          node packageRpm.js