name: Flow Push Branches
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Install 'mingw-w64' to be able to compile for windows
        run: sudo apt-get install mingw-w64
      - name: Build Linux (x64) Binary
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --all-features
      - name: Build Windows (x64) Binary
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --target x86_64-pc-windows-gnu --all-features
      - name: Reduce size of Linux (x64) binary (strip)
        working-directory: target/release
        run: |
          strip todo-cli
      - name: Reduce size of Windows (x64) binary (strip)
        working-directory: target/x86_64-pc-windows-gnu/release
        run: |
          strip todo-cli.exe
      - name: Set up NodeJS   
        uses: actions/setup-node@v2
        with:
          node-version: '16'         
      - name: Install nodejs dependencies
        working-directory: dist/templating
        run: |
          npm install
      - name: Create .deb package
        working-directory: dist/templating
        run: |
          node packageDeb.js
      - name: Create .rpm package
        working-directory: dist/templating
        run: |
          node packageRpm.js