name: Flow Push Branches
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --all-features