name: Flow for tags
on:
  create:
    tags:
      - v*
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --all-features
      - name: Install nodejs dependencies
        working-directory: dist/templating
        run: |
          npm install         
      - name: Create .deb package
        run: |
          chmod +x ./dist/deb/make_deb_file.sh
          ./dist/deb/make_deb_file.sh
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./target/release/*.deb