name: Flow for tags
on:
  create:
    tags:
      - v*
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Install 'mingw-w64' to be able to compile for windows
        run: sudo apt-get install mingw-w64
      - name: Installing 'musl' target
        run: |
          rustup target add x86_64-unknown-linux-musl
      - name: Build Linux (x64) Binary
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --all-features --target x86_64-unknown-linux-musl
      - name: Build Windows (x64) Binary
        uses: actions-rs/cargo@v1
        with:
         command: build
         args: --release --target x86_64-pc-windows-gnu --all-features
      - name: Reduce size of Linux (x64) binary (strip)
        working-directory: target/x86_64-unknown-linux-musl/release/
        run: |
          strip todo
      - name: Reduce size of Windows (x64) binary (strip)
        working-directory: target/x86_64-pc-windows-gnu/release
        run: |
          strip todo.exe
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install nodejs dependencies
        working-directory: dist/templating
        run: |
          npm install         
      - name: Create .deb package
        working-directory: dist/templating
        run: |
          node packageDeb.js
      - name: Create .rpm package
        working-directory: dist/templating
        run: |
          node packageRpm.js
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./target/x86_64-unknown-linux-musl/release/todo-cli_0.6.0_amd64.deb
            ./target/x86_64-unknown-linux-musl/release/rpmbuild/RPMS/x86_64/todo-cli-0.6.0-1.x86_64.rpm
            ./target/x86_64-unknown-linux-musl/release/todo
            ./target/x86_64-pc-windows-gnu/release/todo.exe